version: "3"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && /app/bin/dev"
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    tty: true

  postgres:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

volumes:
  postgresdata: